name: CI/CD PHP ke VPS (workwize)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kode dari GitHub
      uses: actions/checkout@v3

    - name: Upload semua file ke VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASS }}
        source: "./"
        target: "/var/www/html/workwize"
        strip_components: 0
        rm: false
        tar_tmp_path: ""
        overwrite: true

    - name: Import database hanya jika belum ada table
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASS }}
        script: |
          TABLE_COUNT=$(mysql -u root -Nse "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='workwise';")
            if [ "$TABLE_COUNT" -eq 0 ]; then
                echo "Belum ada tabel di database workwise. Mengimpor..."
                mysql -u root workwise < /var/www/html/workwize/database/workwise.sql
            else
                echo "Database workwise sudah punya tabel. Lewati impor."
            fi

