name: CI/CD PHP ke VPS (workwize)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kode dari GitHub
      uses: actions/checkout@v3

    - name: Upload semua file ke VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        source: "."
        target: "/var/www/html/workwize"

    - name: Import database workwise.sql ke MySQL VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        script: |
          mysql -u root workwise < /var/www/html/workwize/database/workwise.sql
